language: ruby
cache: bundler
before_script:
    - rm -rf ./_site
    - bundle update
script:
    - bundle exec jekyll build
deploy:
    provider: pages
    local_dir: ./_site
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
