language: ruby

install:
    - bundle install
before_script:
    - rm -rf public
script:
    - bundle exec jekyll build

deploy:
    provider: pages
    local_dir: public
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
